.TH MPRIS2-STATUS-ICON "1" "September 2015"
.SH NAME
mpris2-status-icon \- Status icon to control mpris2 compatible players
.SH DESCRIPTION
Control any mpris2 compatible player from the notification area.  This
application also serves as an example for the libmpris2client library.

The Media Player Remote Interfacing Specification is a standard
D-Bus interface which aims to provide a common programmatic API for
controlling media players.

It provides a mechanism for discovery, querying and basic playback
control of compliant media players, as well as a tracklist interface
which is used to add context to the active media item.

See http://specifications.freedesktop.org/mpris-spec/2.2/.
.SH AUTHORS
mpris2-status-icon was written by Matias De lellis <mati86dl@gmail.com>. This
manual page was written by Doug Torrance <dtorrance@piedmont.edu> for the
Debian project (but may be used by others).
